version: '3.9'


services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app 
      - dev-static-date:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DH_HOST=db
      - DH_USER=devuser
      - DH_PASSWORD=password
      - DH_DB=devdb
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=password
    volumes:
      - dev-db-data:/var/lib/postgresql/data/

volumes:
  dev-db-data:
  dev-static-date:
