# Generated by Django 3.2.20 on 2023-07-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recepe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepe',
            new_name='Recipe',
        ),
    ]
